import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import GlobalContextProvider from "./GlobalContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Navbar from "@/components/shared/Navbar/Navbar";
import Footer from "@/components/shared/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <GlobalContextProvider>
      <html lang="en" className="scroll-smooth">
        <body className={inter.className}>
          <Navbar />
          <div className="mt-[70px]">
            {children}
            <ToastContainer />
          </div>
          <Footer/>
        </body>
      </html>
    </GlobalContextProvider>
  );
}
